import pumaImage from '../product-images/puma.jpg';
import adidasImage from '../product-images/adidas.jpg';
import nikeImage from '../product-images/nike.jpg';
import vansImage from '../product-images/vans.jpg';
import { Product } from '../models/products-interface';

export const products: Product[] = [
  {
    product_image: pumaImage,
    product_name: "Puma Running Shoes Red 42",
    variants: "Red, Size 42",
    category: "Man Shoes",
    product_type: "Running Shoes",
    stock: "15 in stock",
    stock_status: "low",
    retail_price: "$120.00",
    wholesale_price: "$100.00",
  },
  {
    product_image: pumaImage,
    product_name: "Puma Running Shoes Red 42",
    variants: "Red, Size 42",
    category: "Man Shoes",
    product_type: "Running Shoes",
    stock: "15 in stock",
    stock_status: "in stock",
    retail_price: "$120.00",
    wholesale_price: "$100.00",
  },
  {
    product_image: adidasImage,
    product_name: "Adidas NEO Light Green 36",
    variants: "Light Green, Size 36",
    category: "Woman Shoes",
    product_type: "Casual Shoes",
    stock: "8 in stock",
    stock_status: "low",
    retail_price: "$90.00",
    wholesale_price: "$70.00",
  },
  {
    product_image: adidasImage,
    product_name: "Adidas NEO Light Green 36",
    variants: "Light Green, Size 36",
    category: "Woman Shoes",
    product_type: "Casual Shoes",
    stock: "0 in stock",
    stock_status: "out of stock",
    retail_price: "$80.00",
    wholesale_price: "$70.00",
  },
  {
    product_image: nikeImage,
    product_name: "Nike Air Max 90 White 40",
    variants: "White, Size 40",
    category: "Man Shoes",
    product_type: "Sport Shoes",
    stock: "20 in stock",
    stock_status: "in stock",
    retail_price: "$150.00",
    wholesale_price: "$130.00",
  },
  {
    product_image: nikeImage,
    product_name: "Nike Air Max 90 White 40",
    variants: "White, Size 40",
    category: "Man Shoes",
    product_type: "Sport Shoes",
    stock: "20 in stock",
    stock_status: "in stock",
    retail_price: "$150.00",
    wholesale_price: "$130.00",
  },
  {
    product_image: vansImage,
    product_name: "vans Classic Leather 39",
    variants: "Black, Size 39",
    category: "Man Shoes",
    product_type: "Casual Shoes",
    stock: "5 in stock",
    stock_status: "low",
    retail_price: "$90.00",
    wholesale_price: "$80.00",
  },
  {
    product_image: vansImage,
    product_name: "vans Classic Leather 39",
    variants: "Black, Size 39",
    category: "Man Shoes",
    product_type: "Casual Shoes",
    stock: "5 in stock",
    stock_status: "low",
    retail_price: "$90.00",
    wholesale_price: "$80.00",
  },
  {
    product_image: pumaImage,
    product_name: "Puma Suede Classic 38",
    variants: "Blue, Size 38",
    category: "Unisex Shoes",
    product_type: "Stacked Product",
    stock: "10 in stock",
    stock_status: "in stock",
    retail_price: "$110.00",
    wholesale_price: "$95.00",
  },
  {
    product_image: pumaImage,
    product_name: "Puma Suede Classic 38",
    variants: "Blue, Size 38",
    category: "Unisex Shoes",
    product_type: "Stacked Product",
    stock: "10 in stock",
    stock_status: "in stock",
    retail_price: "$110.00",
    wholesale_price: "$95.00",
  },
];
