# Generated by Django 5.1.2 on 2024-11-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_shelved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
