# Generated by Django 5.1.2 on 2024-10-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='user',
        ),
    ]
