# Generated by Django 5.1.3 on 2024-12-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_created_at_alter_product_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='cost_price',
            new_name='unit_price',
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
