# Generated by Django 5.1.3 on 2024-12-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_cost_price_stock_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='status',
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
