# Generated by Django 5.1.2 on 2024-10-30 09:48

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_category_alter_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
