# Generated by Django 5.1.3 on 2024-12-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_stock_status_alter_stock_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
