# Generated by Django 5.1.2 on 2024-11-20 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_image_remove_product_image_url_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Stock',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='inventory_s_name_f89f23_idx',
            old_name='inventory_p_name_f6a6a1_idx',
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['image_url'], name='inventory_i_image_u_bc3f6a_idx'),
        ),
    ]
